# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveSmallIntegerField()),
                ('precio_oferta', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
